/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Factory } from "./Factory";
export type { InklusivaEstudologia } from "./InklusivaEstudologia";
export * as factories from "./factories";
export { Factory__factory } from "./factories/Factory__factory";
export { InklusivaEstudologia__factory } from "./factories/InklusivaEstudologia__factory";
